name: Build

env:
  MAVEN_MIRROR: ${{ secrets.MAVEN_MIRROR }}
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  COMMON_MAVEN_ARGS: "-e -B --settings .github/mvn-settings.xml --fail-at-end -Dno-format"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.github'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.github'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  check:
    # Check if there are other than .md files changed, if so do run full pipeline
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Check for code changes
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }}
          changes=$(git diff --name-only origin/${{ github.base_ref }} HEAD)
          echo "Changed files: $changes"
          if echo "$changes" | grep -vE '\.(md)$'; then
            echo "::set-output name=code_changed::true"
          else
            echo "::set-output name=code_changed::false"
          fi

  build:
    needs: check
    if: needs.check.outputs.code_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build Artifact
        run: ./mvnw $COMMON_MAVEN_ARGS --file pom.xml verify